import { ImageResponse } from "next/og";

export const runtime = "edge";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

// Share card for the landing page (no external assets — pure JSX).
export default function OG() {
  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        padding: 90,
        background: "#fcf9f4",
        fontFamily: "sans-serif",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 18 }}>
        <div
          style={{
            width: 72,
            height: 72,
            borderRadius: 18,
            background: "#1f1f1f",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: 40,
          }}
        >
          ✒️
        </div>
        <div style={{ fontSize: 44, fontWeight: 800, color: "#1f1f1f" }}>
          Syaahi
        </div>
      </div>
      <div
        style={{
          fontSize: 72,
          fontWeight: 800,
          color: "#1f1f1f",
          marginTop: 28,
          lineHeight: 1.1,
        }}
      >
        Handwritten exam notes, generated by AI.
      </div>
      <div style={{ fontSize: 30, color: "#7b756d", marginTop: 18 }}>
        Your material → thoughtful notes → active practice.
      </div>
    </div>,
    { ...size },
  );
}
